### ISSUE TITLE
How to evaluate the computational complexity of this code?

### ISSUE THREAD

**Issue by TheLovelyWendy** [Lcrypto/EMS-decoder-of-NB-LDPC-codes#2]
The code computes CN in a complex manner which is hard to understand. I've learned the article of 07TCOM and 10TCOM (Low-Complexity Decoding for Non-Binary LDPC Codes in High Order Fields), and I am wondering whether this code matches which article, and how to evaluate the computational complexity of this code? (Considering CN and VN, operations including comparisons, real additions and GF(q) additions)

**Comment by Lcrypto** [comment]
https://www.researchgate.net/publication/43406790_Complexity_Comparison_of_Non-Binary_LDPC_Decoders

**Comment by Lcrypto** [comment]
simplified EMS

**Comment by TheLovelyWendy** [comment]
Thank you so much! It's quite helpful!
